services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: painel-investimentos-db
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "SenhaForte123!"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'SenhaForte123!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20

  init-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    depends_on:
      sqlserver:
        condition: service_healthy
    entrypoint: >
      /bin/bash -c "
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P 'SenhaForte123!' -Q \"IF DB_ID('painel-investimentos-db') IS NULL CREATE DATABASE [painel-investimentos-db];\" -C
      "
    restart: "no"

  keycloak-db:
    image: postgres:16
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - "5433:5432"
    volumes:
      - keycloak_db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U keycloak -d keycloak"]
      interval: 10s
      timeout: 5s
      retries: 20

  keycloak:
    image: quay.io/keycloak/keycloak:26.5.4
    container_name: keycloak
    depends_on:
      keycloak-db:
        condition: service_healthy
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command: ["start-dev", "--import-realm"]
    ports:
      - "8081:8080"
    volumes:
      - ./infra/keycloak/import:/opt/keycloak/data/import

volumes:
  sqlserver_data:
  keycloak_db_data:
