# Banco de Dados
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=SenhaForte123!
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=painel-investimentos-db;encrypt=true;trustServerCertificate=true

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

# OpenAI - Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

quarkus.smallrye-openapi.info-title=Painel de Investimentos API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Painel de Investimentos com Perfil de Risco Din\u00E2mico
quarkus.smallrye-openapi.info-contact-name=Giovanni Duarte

quarkus.smallrye-openapi.servers=http://localhost:8080