# Banco de Dados
quarkus.datasource.db-kind=mssql
quarkus.datasource.username=sa
quarkus.datasource.password=SenhaForte123!
quarkus.datasource.jdbc.url=jdbc:sqlserver://localhost:1433;databaseName=painel-investimentos-db;encrypt=true;trustServerCertificate=true

# Hibernate ORM
quarkus.hibernate-orm.schema-management.strategy=none
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=no-file

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.locations=db/migration

# OpenAI - Swagger
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger-ui

# OIDC app client (dev)
%dev.quarkus.oidc.client-id=simulador-api
%dev.quarkus.oidc.credentials.secret=simulador-secret
%dev.quarkus.oidc.application-type=service

# Keycloak Dev Services
%dev.quarkus.keycloak.devservices.enabled=true
%dev.quarkus.keycloak.devservices.shared=false
%dev.quarkus.keycloak.devservices.admin-username=admin
%dev.quarkus.keycloak.devservices.admin-password=admin
